int addone(int n);
int fibonacci(int n);
int * pairs();
void print_tableau(int t[], int n);
void sum_array(int t0[], int t1[], int result[], int n);
void print_input();
int mylen(const char s[]);
int compare_string(const char s0[], const char s1[]);
int is_palyndrome(const char s[]);
int one_bits(int n);